version: "3"

services:
  meal_manager_mongo:
    image: mongo
    container_name: meal_manager_mongo
    environment:
      - discovery.type=single-node
    networks:
      meal_manager_net:
        ipv4_address: 172.21.0.2
    ports:
      - 3001:27017
  meal_manager:
    build: .
    volumes:
      - .:/usr/src/app/meal-manager
    command: python3 meal-manager/meal-manager.py
    depends_on:
      - meal_manager_mongo
    networks:
      meal_manager_net:
        ipv4_address: 172.21.0.3
    ports:
      - 1234:9000
      
networks:
  meal_manager_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1